// ============================================
// Composite Shape: Composed_a_snowman
// Generated by RAG Composition Engine
// Components: 7
// ============================================

float2 p = UV - Center;
    float d = length(p) - Radius;
    
    // Calculate anti-aliasing softness based on screen derivatives
    float aa = fwidth(d);
    aa = max(aa, 0.001); // Safety clamp to prevent division by zero or extremely hard edges
    
    // Smoothstep for AA: 1.0 inside (negative dist), 0.0 outside (positive dist)
    // Centered at 0: range [aa, -aa]
    float edge = smoothstep(aa, -aa, d);
    
    outColor = float4(Color.rgb * edge, edge);
}

float sdHeart(float2 p) {
    p.x = abs(p.x);
    // Upper lobes
    if (p.y + p.x > 1.0)
        return sqrt(dot2(p - float2(0.25, 0.75))) - sqrt(2.0)/4.0;
    // Lower point
    return sqrt(min(dot2(p - float2(0.00, 1.00)),
                    dot2(p - 0.5 * max(p.x + p.y, 0.0)))) * sign(p.x - p.y);
}

float2 p = UV - Center;
    
    float c = cos(Rotation);
    float s = sin(Rotation);
    p = float2(c * p.x + s * p.y, -s * p.x + c * p.y);
    
    // 2. Scale and Proportions
    // Scale 'p' so that the shape fits the Size.
    // Size of 1.0 roughly fills the screen.
    p /= max(Size, 0.001);
    
    // Adjust for aspect ratio (width vs height)
    // Proportions.x controls width, .y controls height
    p /= max(Proportions, 0.001);
    
    // 3. Visual Centering
    // The mathematical heart SDF sits roughly at y=[0, 1] with tip at (0,0).
    // We shift y by +0.5 to move the visual center to (0,0).
    p.y += 0.5;
    
    // 4. Calculate SDF
    float d = sdHeart(p);
    
    // 5. Band Logic
    // Convert to positive distance inside the shape
    float distInside = -d;
    
    // Analytic Anti-Aliasing width
    float aa = fwidth(distInside);
    
    // 6. Masks
    // Outer shape edge mask (0 outside, 1 inside)
    float shapeMask = smoothstep(-aa, 0.0, distInside);
    
    // Concentric Bands
    // Map distance to repeating band intervals
    float bandCoords = distInside * max(BandCount, 1.0);
    float bandVal = frac(bandCoords);
    
    // Band AA (relative to band frequency)
    float bandAA = fwidth(bandCoords);
    
    // Create the band fill based on thickness (0 to 1)
    // Fills from the start of the interval up to Thickness
    float bandMask = smoothstep(BandThickness + bandAA, BandThickness, bandVal);
    // Combine with 'step(0, bandVal)' implicit in smoothstep range, 
    // but we need to ensure the gap is transparent.
    // Logic: if bandVal < Thickness -> 1, else -> 0.
    // Note: bandMask is 1 when bandVal is small (start of band).
    
    // 7. Coloring
    // Gradient from center (high distInside) to edge (low distInside)
    // Normalize roughly: Heart radius is approx 0.6 in SDF space.
    float gradT = saturate(distInside * 1.5);
    float4 finalRGB = lerp(OuterColor, InnerColor, gradT);
    
    // Final Composition
    float finalAlpha = shapeMask * bandMask;
    
    // Pre-multiply alpha for correct blending if needed, or output straight alpha
    // Standard Unity UI/Sprite usually expects straight alpha in shader graph if Blend Mode is Alpha.
    // Here we output (RGB * Alpha, Alpha) pattern just in case.
    outColor = float4(finalRGB.rgb * finalAlpha, finalAlpha);
}

float2 q = abs(p) - b + r;
    return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r;
}

float sdEllipseApprox(float2 p, float2 r) {
    float k0 = length(p / max(r, 0.0001));
    return (k0 - 1.0) * min(r.x, r.y);
}

float2 brimP = p - float2(0.0, crownBaseY);
    // Apply curvature: bend Y downwards based on X distance squared
    brimP.y -= -BrimCurvature * (brimP.x * brimP.x);
    
    // Wide flattened ellipse for brim
    float brimThickness = 0.02;
    float dBrim = sdEllipseApprox(brimP, float2(BrimWidth * 0.5, brimThickness));
    
    // 5. Combine Shapes
    // Smooth union to blend brim and crown organically
    float dShape = smin(dCrown, dBrim, 0.04);
    
    // 6. Rendering / Coloring
    float aa = fwidth(dShape);
    
    // -- Mask for Hatband --
    // Band sits at the base of the crown. We check vertical range relative to crown base.
    // We strictly mask it to the Crown shape (dCrown) to avoid painting the brim.
    float bandLocalY = p.y - crownBaseY;
    float inBandY = step(0.0, bandLocalY) * step(bandLocalY, BandThickness);
    // To ensure band doesn't bleed onto the wide brim, we check if we are 'physically' in the crown area
    // Simple approximation: check if dCrown is smaller (dominant) than dBrim
    float isCrownDom = step(dCrown, dBrim + 0.01);
    float bandMask = inBandY * isCrownDom;
    
    // -- Fill Color --
    float4 finalFill = lerp(HatColor, BandColor, bandMask);
    float fillAlpha = 1.0 - smoothstep(0.0, aa, dShape);
    float4 fillLayer = float4(finalFill.rgb, finalFill.a * fillAlpha);
    
    // -- Outline Stroke --
    // Center the stroke on the edge (d=0). Width is total width.
    float halfStroke = max(OutlineWidth, 0.0) * 0.5;
    float strokeDist = abs(dShape) - halfStroke;
    float strokeAlpha = 1.0 - smoothstep(0.0, aa, strokeDist);
    float4 strokeLayer = float4(OutlineColor.rgb, OutlineColor.a * strokeAlpha);
    
    // 7. Composite Stroke over Fill
    outColor = compositeOver(strokeLayer, fillLayer);
}

float2 rotate(float2 p, float a) {
    float c = cos(a);
    float s = sin(a);
    return float2(c * p.x - s * p.y, s * p.x + c * p.y);
}

float sdUnevenCapsule(float2 p, float r1, float r2, float h) {
    p.x = abs(p.x);
    float b = (r1 - r2) / h;
    float a = sqrt(1.0 - b * b);
    float k = dot(p, float2(-b, a));
    if (k < 0.0) return length(p) - r1;
    if (k > a * h) return length(p - float2(0.0, h)) - r2;
    return dot(p, float2(a, b)) - r1;
}

float sdVesica(float2 p, float w, float l) {
    // Ensure safe values
    w = max(w, 0.001);
    l = max(l, 0.001);
    
    // Calculate radius and offset for the intersecting circles
    float r = (l * l + w * w) / (4.0 * w);
    float d = r - w * 0.5;
    
    p = abs(p);
    float b = sqrt(max(r * r - d * d, 0.0)); // half length
    
    // SDF Logic
    return ((p.y - b) * d > p.x * b) ? length(p - float2(0.0, b))
                                     : length(p - float2(-d, 0.0)) - r;
}

float2 pL = rotate(leafOrigin, ang);
        
        // Offset y so the leaf base sits at the origin
        // The vesica function centers the shape, so we shift by half length.
        pL.y -= LeafLength * 0.5;
        
        float dL = sdVesica(pL, LeafWidth, LeafLength);
        dLeaves = min(dLeaves, dL);
    }

float2 rot2D(float2 p, float angle) {
    float c = cos(angle);
    float s = sin(angle);
    return float2(c * p.x - s * p.y, s * p.x + c * p.y);
}

float2 ba = b - a;
    float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
    return length(pa - ba * h);
}

float2 knobPos = float2(Length, KnobOffset);
    float dKnob = length(q - knobPos) - KnobSize;

    // 6) Blend
    // k = 0.05 provides a cartilage-like smooth transition between shaft and knobs
    float dist = smin(dShaft, dKnob, 0.05);

    // 7) Output
    // Smoothstep for crisp but anti-aliased edges
    float edge = smoothstep(0.01, -0.01, dist);
    
    // Final composite (Color * alpha, alpha)
    outColor = float4(Color.rgb * edge, edge * Color.a);
}

float2 d = abs(p) - b;
    return length(max(d, 0.0)) + min(max(d.x, d.y), 0.0);
}

float2 rotate(float2 p, float angle) {
    float c = cos(angle);
    float s = sin(angle);
    return float2(c * p.x - s * p.y, s * p.x + c * p.y);
}

float2 pRot = rotate(p, radians(45.0));
    
    // Dimensions for the X arms
    // xHalfLen is the distance from center to tip of the X arm
    float xHalfLen = Size * XScale;
    // xHalfThick is half the width of the stroke
    float xHalfThick = Thickness * 0.5;
    
    // Calculate SDFs for two crossing boxes
    float dBox1 = sdBox(pRot, float2(xHalfLen, xHalfThick)); // Arm 1
    float dBox2 = sdBox(pRot, float2(xHalfThick, xHalfLen)); // Arm 2
    
    // Union of the two boxes (min distance)
    float dX = min(dBox1, dBox2);
    
    float xAA = fwidth(dX);
    // Soft mask for X (1.0 inside, 0.0 outside)
    float alphaX = 1.0 - smoothstep(-xAA, xAA, dX);

    // 4. Composite Colors (Premultiplied Alpha)
    // Prepare Background Color (Circle)
    float4 bg = float4(BackgroundColor.rgb * BackgroundColor.a * alphaCircle, BackgroundColor.a * alphaCircle);
    
    // Prepare Foreground Color (X)
    float4 fg = float4(XColor.rgb * XColor.a * alphaX, XColor.a * alphaX);
    
    // Blend X over Circle using standard "Source Over" blending:
    // Result = Foreground + Background * (1 - ForegroundAlpha)
    outColor = fg + bg * (1.0 - fg.a);
}

// Component 0: Circle
float Component0_SDF(float2 uv, float2 offset, float scale, float rotation)
{
    // Apply transformations
    uv -= offset;
    uv /= scale;
    
    if (rotation != 0.0)
    {
        float c = cos(rotation);
        float s = sin(rotation);
        uv = float2(uv.x * c - uv.y * s, uv.x * s + uv.y * c);
    }
    
    // Call original SDF
        // User Request: a circle
        // PLAN:
        // 1) Offset UV by Center to get local coordinates p.
        // 2) Calculate signed distance field (SDF) for a circle: length(p) - radius.
        // 3) Calculate anti-aliasing width using fwidth for sharp edges.
        // 4) Compute alpha mask using smoothstep centered on the edge.
        // 5) Output final color with premultiplied alpha.
    
        float2 p = UV - Center;
        float d = length(p) - Radius;
        
        // Calculate anti-aliasing softness based on screen derivatives
        float aa = fwidth(d);
        aa = max(aa, 0.001); // Safety clamp to prevent division by zero or extremely hard edges
        
        // Smoothstep for AA: 1.0 inside (negative dist), 0.0 outside (positive dist)
        // Centered at 0: range [aa, -aa]
        float edge = smoothstep(aa, -aa, d);
        
    }
    
    
    return d;
}

// Component 1: ConcentricHeartShape
float Component1_SDF(float2 uv, float2 offset, float scale, float rotation)
{
    // Apply transformations
    uv -= offset;
    uv /= scale;
    
    if (rotation != 0.0)
    {
        float c = cos(rotation);
        float s = sin(rotation);
        uv = float2(uv.x * c - uv.y * s, uv.x * s + uv.y * c);
    }
    
    // Call original SDF
        float2 UV,
        float2 Center,
        float Size,
        float2 Proportions,
        float Rotation,
        float BandCount,
        float BandThickness,
        float4 InnerColor,
        float4 OuterColor,
        out float4 outColor
    ) {
        // 1. Center and Rotate
        float2 p = UV - Center;
        
        float c = cos(Rotation);
        float s = sin(Rotation);
        p = float2(c * p.x + s * p.y, -s * p.x + c * p.y);
        
        // 2. Scale and Proportions
        // Scale 'p' so that the shape fits the Size.
        // Size of 1.0 roughly fills the screen.
        p /= max(Size, 0.001);
        
        // Adjust for aspect ratio (width vs height)
        // Proportions.x controls width, .y controls height
        p /= max(Proportions, 0.001);
        
        // 3. Visual Centering
        // The mathematical heart SDF sits roughly at y=[0, 1] with tip at (0,0).
        // We shift y by +0.5 to move the visual center to (0,0).
        p.y += 0.5;
        
        // 4. Calculate SDF
        float d = sdHeart(p);
        
        // 5. Band Logic
        // Convert to positive distance inside the shape
        float distInside = -d;
        
        // Analytic Anti-Aliasing width
        float aa = fwidth(distInside);
        
        // 6. Masks
        // Outer shape edge mask (0 outside, 1 inside)
        float shapeMask = smoothstep(-aa, 0.0, distInside);
        
        // Concentric Bands
        // Map distance to repeating band intervals
        float bandCoords = distInside * max(BandCount, 1.0);
        float bandVal = frac(bandCoords);
        
        // Band AA (relative to band frequency)
        float bandAA = fwidth(bandCoords);
        
        // Create the band fill based on thickness (0 to 1)
        // Fills from the start of the interval up to Thickness
        float bandMask = smoothstep(BandThickness + bandAA, BandThickness, bandVal);
        // Combine with 'step(0, bandVal)' implicit in smoothstep range, 
        // but we need to ensure the gap is transparent.
        // Logic: if bandVal < Thickness -> 1, else -> 0.
        // Note: bandMask is 1 when bandVal is small (start of band).
        
        // 7. Coloring
        // Gradient from center (high distInside) to edge (low distInside)
        // Normalize roughly: Heart radius is approx 0.6 in SDF space.
        float gradT = saturate(distInside * 1.5);
        float4 finalRGB = lerp(OuterColor, InnerColor, gradT);
        
        // Final Composition
        float finalAlpha = shapeMask * bandMask;
        
        // Pre-multiply alpha for correct blending if needed, or output straight alpha
        // Standard Unity UI/Sprite usually expects straight alpha in shader graph if Blend Mode is Alpha.
        // Here we output (RGB * Alpha, Alpha) pattern just in case.
    
    
    return d;
}

// Component 2: Circle
float Component2_SDF(float2 uv, float2 offset, float scale, float rotation)
{
    // Apply transformations
    uv -= offset;
    uv /= scale;
    
    if (rotation != 0.0)
    {
        float c = cos(rotation);
        float s = sin(rotation);
        uv = float2(uv.x * c - uv.y * s, uv.x * s + uv.y * c);
    }
    
    // Call original SDF
        // User Request: a circle
        // PLAN:
        // 1) Offset UV by Center to get local coordinates p.
        // 2) Calculate signed distance field (SDF) for a circle: length(p) - radius.
        // 3) Calculate anti-aliasing width using fwidth for sharp edges.
        // 4) Compute alpha mask using smoothstep centered on the edge.
        // 5) Output final color with premultiplied alpha.
    
        float2 p = UV - Center;
        float d = length(p) - Radius;
        
        // Calculate anti-aliasing softness based on screen derivatives
        float aa = fwidth(d);
        aa = max(aa, 0.001); // Safety clamp to prevent division by zero or extremely hard edges
        
        // Smoothstep for AA: 1.0 inside (negative dist), 0.0 outside (positive dist)
        // Centered at 0: range [aa, -aa]
        float edge = smoothstep(aa, -aa, d);
        
    }
    
    
    return d;
}

// Component 3: FedoraHat
float Component3_SDF(float2 uv, float2 offset, float scale, float rotation)
{
    // Apply transformations
    uv -= offset;
    uv /= scale;
    
    if (rotation != 0.0)
    {
        float c = cos(rotation);
        float s = sin(rotation);
        uv = float2(uv.x * c - uv.y * s, uv.x * s + uv.y * c);
    }
    
    // Call original SDF
        // 1. Center and Scale UV
        float2 p = (UV - 0.5) * 2.0;
        p /= max(Size, 0.0001);
        
        // 2. Define Dimensions & Anchors
        float halfCW = CrownWidth * 0.5;
        float halfCH = CrownHeight * 0.5;
        float2 crownCenter = float2(0.0, 0.1); // Shift up slightly to fit brim
        float crownBaseY = crownCenter.y - halfCH;
        
        // 3. Crown SDF
        // Base rounded box
        float roundness = 0.15 * CrownWidth;
        float dCrownBase = sdRoundBox(p - crownCenter, float2(halfCW, halfCH), roundness);
        
        // Indent (Concave top)
        // Subtract a sphere from the top center
        // Position the sphere so it cuts into the top edge
        float indentRadius = halfCW * 0.9;
        float2 indentPos = crownCenter + float2(0.0, halfCH + indentRadius - CrownIndent);
        float dIndentSphere = length(p - indentPos) - indentRadius;
        
        // Apply smooth subtraction: max(Crown, -Indent)
        float dCrown = smax(dCrownBase, -dIndentSphere, 0.08);
        
        // 4. Brim SDF
        // Local coordinates for brim, anchored at crown base
        float2 brimP = p - float2(0.0, crownBaseY);
        // Apply curvature: bend Y downwards based on X distance squared
        brimP.y -= -BrimCurvature * (brimP.x * brimP.x);
        
        // Wide flattened ellipse for brim
        float brimThickness = 0.02;
        float dBrim = sdEllipseApprox(brimP, float2(BrimWidth * 0.5, brimThickness));
        
        // 5. Combine Shapes
        // Smooth union to blend brim and crown organically
        float dShape = smin(dCrown, dBrim, 0.04);
        
        // 6. Rendering / Coloring
        float aa = fwidth(dShape);
        
        // -- Mask for Hatband --
        // Band sits at the base of the crown. We check vertical range relative to crown base.
        // We strictly mask it to the Crown shape (dCrown) to avoid painting the brim.
        float bandLocalY = p.y - crownBaseY;
        float inBandY = step(0.0, bandLocalY) * step(bandLocalY, BandThickness);
        // To ensure band doesn't bleed onto the wide brim, we check if we are 'physically' in the crown area
        // Simple approximation: check if dCrown is smaller (dominant) than dBrim
        float isCrownDom = step(dCrown, dBrim + 0.01);
        float bandMask = inBandY * isCrownDom;
        
        // -- Fill Color --
        float4 finalFill = lerp(HatColor, BandColor, bandMask);
        float fillAlpha = 1.0 - smoothstep(0.0, aa, dShape);
        float4 fillLayer = float4(finalFill.rgb, finalFill.a * fillAlpha);
        
        // -- Outline Stroke --
        // Center the stroke on the edge (d=0). Width is total width.
        float halfStroke = max(OutlineWidth, 0.0) * 0.5;
        float strokeDist = abs(dShape) - halfStroke;
        float strokeAlpha = 1.0 - smoothstep(0.0, aa, strokeDist);
        float4 strokeLayer = float4(OutlineColor.rgb, OutlineColor.a * strokeAlpha);
        
        // 7. Composite Stroke over Fill
    }
    
    // ------------------------------------------------------------------------
    //  Visual Result
    // ------------------------------------------------------------------------
    //  This function generates a **stylized cartoon fedora** using 
    //  Signed Distance Functions (SDFs).
    //
    //  The visual result is composed of:
    //  - A central **crown** featuring a characteristic concave indentation 
    //    (pinch) at the top.
    //  - A wide, curved **brim** extending outward from the base of the crown.
    //  - A decorative **hat band** (ribbon) wrapping around the bottom of the 
    //    crown, distinct from the main hat color.
    //
    //  The shape features adjustable parameters for the crown dimensions and 
    //  indent depth, the width and curvature of the brim, and the thickness of 
    //  the hat band.
    //
    //  The output is a flat-shaded graphic with a cohesive outline that creates
    //  a smooth, organic union between the brim and the crown, suitable for 
    //  detective icons, noir themes, or character accessories.
    // ------------------------------------------------------------------------
    
    
    return d;
}

// Component 4: CartoonCarrot
float Component4_SDF(float2 uv, float2 offset, float scale, float rotation)
{
    // Apply transformations
    uv -= offset;
    uv /= scale;
    
    if (rotation != 0.0)
    {
        float c = cos(rotation);
        float s = sin(rotation);
        uv = float2(uv.x * c - uv.y * s, uv.x * s + uv.y * c);
    }
    
    // Call original SDF
        // PLAN:
        // 1) Remap UV to centered coordinates and scale.
        // 2) Construct Body SDF (Uneven Capsule) oriented vertically.
        // 3) Construct Leaf Cluster SDF by rotating Vesica shapes from the body top.
        // 4) Combine Body and Leaves into a single union SDF for the outline.
        // 5) Generate Notch markings mask using sine pattern on body Y coords.
        // 6) Resolve colors: Determine if pixel is Body or Leaf, apply notches, then add outline.
        
        // 1. Center and Scale
        // Center UV at (0.5, 0.5) and apply inverse scale
        float2 p = (UV - 0.5) * (2.0 / max(Size, 0.001));
        
        // 2. Body SDF construction
        // The body is an uneven capsule defined from y=0 (Tip) to y=Height (Top).
        // We visually center the carrot by offsetting p.
        float h = max(BodyLength, 0.01);
        float rTop = max(BodyTopWidth, 0.0);
        float rTip = max(BodyTipRadius, 0.0);
        
        // Map screen space to SDF space: 
        // Shift y so that the visual center of the carrot aligns with screen center.
        // Placing the Tip at local y=0 means shifting p up by h/2 roughly.
        float2 pBody = p;
        pBody.y += h * 0.5;
        
        float dBody = sdUnevenCapsule(pBody, rTip, rTop, h);
        
        // 3. Leaf Cluster SDF construction
        // Leaves grow from the top of the body (y = h in pBody space).
        float2 leafOrigin = pBody - float2(0.0, h);
        float dLeaves = 1000.0;
        int count = max(1, (int)LeafCount);
        float spread = LeafSpread * 0.5;
        
        // Loop to create fan of leaves
        for (int i = 0; i < count; i++) {
            // Calculate angle for this leaf
            float t = (count > 1) ? (float(i) / float(count - 1)) : 0.5;
            float ang = lerp(-spread, spread, t);
            
            // Rotate position relative to leaf origin
            float2 pL = rotate(leafOrigin, ang);
            
            // Offset y so the leaf base sits at the origin
            // The vesica function centers the shape, so we shift by half length.
            pL.y -= LeafLength * 0.5;
            
            float dL = sdVesica(pL, LeafWidth, LeafLength);
            dLeaves = min(dLeaves, dL);
    
    
    return d;
}

// Component 5: CartoonBone
float Component5_SDF(float2 uv, float2 offset, float scale, float rotation)
{
    // Apply transformations
    uv -= offset;
    uv /= scale;
    
    if (rotation != 0.0)
    {
        float c = cos(rotation);
        float s = sin(rotation);
        uv = float2(uv.x * c - uv.y * s, uv.x * s + uv.y * c);
    }
    
    // Call original SDF
        // PLAN:
        // 1) Translate UVs to centered coordinates.
        // 2) Rotate coordinates.
        // 3) Apply 4-way symmetry (abs(p)) to model one quadrant (top-right).
        // 4) Define Shaft as a horizontal segment on X-axis.
        // 5) Define Knob as a circle offset vertically from the shaft end.
        // 6) Smoothly blend Shaft and Knob to form the bone.
        // 7) Apply anti-aliasing and coloring.
    
        // 1) Centering
        float2 p = UV - Center;
    
        // 2) Rotation
        p = rot2D(p, -Rotation); // -Rotation for intuitive CCW spin
    
        // 3) Symmetry: Reflect X and Y
        // This folds the 4 quadrants into the top-right quadrant (+X, +Y)
        // This ensures we get a knob at Top-Right, Top-Left, Bottom-Right, Bottom-Left automatically.
        float2 q = abs(p);
    
        // 4) Shaft SDF
        // Segment from center (0,0) to (Length, 0).
        // Subtract Thickness to give it width.
        float dShaft = sdSegment(q, float2(0.0, 0.0), float2(Length, 0.0)) - Thickness;
    
        // 5) Knob SDF
        // We place a circle at x=Length.
        // y=KnobOffset moves it up/down relative to shaft center.
        // Because we used abs(p.y), this single circle mirrors to create the "heart-like" end of the bone.
        float2 knobPos = float2(Length, KnobOffset);
        float dKnob = length(q - knobPos) - KnobSize;
    
        // 6) Blend
        // k = 0.05 provides a cartilage-like smooth transition between shaft and knobs
        float dist = smin(dShaft, dKnob, 0.05);
    
        // 7) Output
        // Smoothstep for crisp but anti-aliased edges
        float edge = smoothstep(0.01, -0.01, dist);
        
        // Final composite (Color * alpha, alpha)
    }
    
    // ------------------------------------------------------------------------
    //  Visual Result (High-level, parameter-invariant description)
    // ------------------------------------------------------------------------
    //  This function generates a **stylized 2D cartoon bone-like primitive**
    //  using Signed Distance Functions (SDFs).
    //
    //  The shape consists of a straight central shaft with rounded, bulb-like
    //  ends on both sides, forming a classic bone silhouette. The overall
    //  length, shaft thickness, end-knob size, end offset, rotation,
    //  placement, and color are fully controlled by input parameters and are
    //  not fixed by the function itself.
    //
    //  The output is an anti-aliased RGBA color suitable for playful icons,
    //  game UI elements, decorative symbols, and expressive procedural
    //  2D graphics.
    // ------------------------------------------------------------------------
    
    
    
    return d;
}

// Component 6: RoundCloseIcon
float Component6_SDF(float2 uv, float2 offset, float scale, float rotation)
{
    // Apply transformations
    uv -= offset;
    uv /= scale;
    
    if (rotation != 0.0)
    {
        float c = cos(rotation);
        float s = sin(rotation);
        uv = float2(uv.x * c - uv.y * s, uv.x * s + uv.y * c);
    }
    
    // Call original SDF
        // PLAN:
        // 1) Center UVs to (0,0).
        // 2) Compute Circle SDF for the background.
        // 3) Compute X SDF (Union of two rotated boxes) for the foreground.
        // 4) Compute Anti-aliased masks for both shapes.
        // 5) Composite Foreground (X) over Background (Circle) using premultiplied alpha blending.
    
        // 1. Center UV coordinates (0.5, 0.5 becomes 0,0)
        float2 p = UV - 0.5;
    
        // 2. Circle SDF (Background)
        // Distance from center minus radius (Size)
        float dCircle = length(p) - Size;
        float circleAA = fwidth(dCircle);
        // Soft mask for circle (1.0 inside, 0.0 outside)
        float alphaCircle = 1.0 - smoothstep(-circleAA, circleAA, dCircle);
    
        // 3. X Shape SDF (Foreground)
        // Rotate point by 45 degrees to turn a + into an X
        float2 pRot = rotate(p, radians(45.0));
        
        // Dimensions for the X arms
        // xHalfLen is the distance from center to tip of the X arm
        float xHalfLen = Size * XScale;
        // xHalfThick is half the width of the stroke
        float xHalfThick = Thickness * 0.5;
        
        // Calculate SDFs for two crossing boxes
        float dBox1 = sdBox(pRot, float2(xHalfLen, xHalfThick)); // Arm 1
        float dBox2 = sdBox(pRot, float2(xHalfThick, xHalfLen)); // Arm 2
        
        // Union of the two boxes (min distance)
        float dX = min(dBox1, dBox2);
        
        float xAA = fwidth(dX);
        // Soft mask for X (1.0 inside, 0.0 outside)
        float alphaX = 1.0 - smoothstep(-xAA, xAA, dX);
    
        // 4. Composite Colors (Premultiplied Alpha)
        // Prepare Background Color (Circle)
        float4 bg = float4(BackgroundColor.rgb * BackgroundColor.a * alphaCircle, BackgroundColor.a * alphaCircle);
        
        // Prepare Foreground Color (X)
        float4 fg = float4(XColor.rgb * XColor.a * alphaX, XColor.a * alphaX);
        
        // Blend X over Circle using standard "Source Over" blending:
        // Result = Foreground + Background * (1 - ForegroundAlpha)
    }
    
    
    return d;
}

void Composed_a_snowman_float(
    float2 UV,
    float2 Component0_Offset,
    float Component0_Scale,
    float Component0_Rotation,
    float2 Component1_Offset,
    float Component1_Scale,
    float Component1_Rotation,
    float2 Component2_Offset,
    float Component2_Scale,
    float Component2_Rotation,
    float2 Component3_Offset,
    float Component3_Scale,
    float Component3_Rotation,
    float2 Component4_Offset,
    float Component4_Scale,
    float Component4_Rotation,
    float2 Component5_Offset,
    float Component5_Scale,
    float Component5_Rotation,
    float2 Component6_Offset,
    float Component6_Scale,
    float Component6_Rotation,
    float4 Color,
    out float4 Out
)
{
    float2 uv = UV - 0.5;

    float d0 = Component0_SDF(uv, Component0_Offset, Component0_Scale, Component0_Rotation);
    float d1 = Component1_SDF(uv, Component1_Offset, Component1_Scale, Component1_Rotation);
    float d2 = Component2_SDF(uv, Component2_Offset, Component2_Scale, Component2_Rotation);
    float d3 = Component3_SDF(uv, Component3_Offset, Component3_Scale, Component3_Rotation);
    float d4 = Component4_SDF(uv, Component4_Offset, Component4_Scale, Component4_Rotation);
    float d5 = Component5_SDF(uv, Component5_Offset, Component5_Scale, Component5_Rotation);
    float d6 = Component6_SDF(uv, Component6_Offset, Component6_Scale, Component6_Rotation);

    // Combine all components using smooth union
    float finalDistance = d0;
    finalDistance = min(finalDistance, d1); // Union operation
    finalDistance = min(finalDistance, d2); // Union operation
    finalDistance = min(finalDistance, d3); // Union operation
    finalDistance = min(finalDistance, d4); // Union operation
    finalDistance = min(finalDistance, d5); // Union operation
    finalDistance = min(finalDistance, d6); // Union operation

    // Anti-aliased rendering
    float alpha = smoothstep(0.01, -0.01, finalDistance);
    Out = float4(Color.rgb, alpha * Color.a);
}

