using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using UnityEditor;
using UnityEngine;
using Newtonsoft.Json;
using ShaderGraphGenerator.KnowledgeBase;
using ShaderGraphGenerator.Editor;

namespace ShaderGraphGenerator.RAG
{
    // ─── result data model ────────────────────────────────────────────────────

    public class HLSLUpdateResult
    {
        public string updateRequest;
        public string originalFileName;
        public string originalHlslCode;
        public string updatedFileName;
        public string updatedHlslCode;
        public List<LLMShaderProperty> properties;
        public string shaderGraphPath;
        public string materialPath;
        public string beforeImagePath;
        public string afterImagePath;
        public int    vlmScore;
        public string vlmFeedback;
        public bool   success;       // true = VLM score > 7
        public string errorMessage;
    }

    // ─── pipeline ─────────────────────────────────────────────────────────────

    public static class HLSLUpdatePipelineManager
    {
        private const string UPDATE_DIR  = "Assets/ShaderGraphs/RAG_Updates";
        private const string PREVIEW_DIR = "Assets/ShaderGraphs/Previews";

        private const int VLM_ACCEPT_THRESHOLD = 7; // score must be > this to accept

        /// <summary>
        /// Full update pipeline:
        ///   1. Extract HLSL and current property values from the source material.
        ///   2. Render BEFORE screenshot directly from the original material.
        ///   3. Retrieve relevant KB examples.
        ///   4. LLM loop (up to maxVlmIterations): generate updated HLSL → render AFTER → VLM compare.
        ///   5. Return result. Score > 7 = success.
        /// </summary>
        public static async Task<HLSLUpdateResult> RunUpdatePipelineAsync(
            Material originalMaterial,
            string   updateRequest,
            ShapeKnowledgeBase knowledgeBase,
            ShaderGraphGeneratorConfig config,
            int    maxVlmIterations = 1,
            string userFeedback     = null)
        {
            var result = new HLSLUpdateResult
            {
                updateRequest    = updateRequest,
                originalFileName = originalMaterial != null ? originalMaterial.name : "unknown"
            };

            try
            {
                EnsureDirectories();

                // ── 1. Extract HLSL from the material's ShaderGraph ───────────
                if (originalMaterial == null)
                {
                    result.errorMessage = "No material provided.";
                    return result;
                }

                string originalHlslPath = ExtractHlslPathFromMaterial(originalMaterial);
                if (string.IsNullOrEmpty(originalHlslPath))
                {
                    result.errorMessage =
                        "Could not find an HLSL Custom Function source in this material's ShaderGraph. " +
                        "Make sure the shader was generated by this tool.";
                    return result;
                }

                string originalHlsl = File.ReadAllText(originalHlslPath);
                result.originalHlslCode = originalHlsl;
                result.originalFileName  = Path.GetFileNameWithoutExtension(originalHlslPath);
                Debug.Log($"[Update Pipeline] HLSL source: {originalHlslPath}");

                // ── 2. Extract current material property values ───────────────
                var originalProperties = ExtractMaterialProperties(originalMaterial);
                Debug.Log($"[Update Pipeline] Extracted {originalProperties.Count} properties from material.");

                // ── 3. Render BEFORE screenshot from the original material ────
                Debug.Log("[Update Pipeline] Rendering BEFORE screenshot…");
                string beforePath    = Path.Combine(PREVIEW_DIR, $"{result.originalFileName}_before.png");
                string beforeAbsPath = ToAbsolutePath(beforePath);
                Directory.CreateDirectory(Path.GetDirectoryName(beforeAbsPath));
                bool beforeOk = await RenderMaterialToImageAsync(originalMaterial, beforeAbsPath, keepQuad: false);
                result.beforeImagePath = beforeOk && File.Exists(beforeAbsPath) ? beforeAbsPath : null;

                // ── 4. Retrieve relevant KB examples ──────────────────────────
                Debug.Log("[Update Pipeline] Retrieving KB examples for update…");
                var examples = await RetrieveExamplesAsync(updateRequest, knowledgeBase, config.openAIKey);

                // ── 5. VLM-guided iteration loop ──────────────────────────────
                string currentHlsl         = originalHlsl;
                string previousVlmFeedback = null;

                for (int iter = 1; iter <= maxVlmIterations; iter++)
                {
                    Debug.Log($"[Update Pipeline] VLM iteration {iter}/{maxVlmIterations}");

                    // 5a. Ask LLM to produce updated HLSL
                    string prompt = BuildUpdatePrompt(
                        originalHlsl, currentHlsl, updateRequest,
                        originalProperties, examples,
                        previousVlmFeedback, userFeedback, iter);

                    string jsonRaw = await LLMApiService.CallGeminiAsync(prompt, config.geminiKey);
                    if (string.IsNullOrEmpty(jsonRaw))
                    {
                        result.errorMessage = "LLM returned an empty response.";
                        return result;
                    }
                    jsonRaw = StripMarkdown(jsonRaw);

                    LLMShaderResponse llmResponse;
                    try { llmResponse = JsonConvert.DeserializeObject<LLMShaderResponse>(jsonRaw); }
                    catch (Exception ex)
                    {
                        Debug.LogError($"[Update Pipeline] JSON parse error: {ex.Message}\n{jsonRaw}");
                        continue; // try again
                    }

                    // 5b. Save updated HLSL
                    string updatedHlslPath = Path.Combine(UPDATE_DIR, $"{llmResponse.file_name}.hlsl");
                    File.WriteAllText(updatedHlslPath, llmResponse.hlsl_code);
                    AssetDatabase.Refresh();

                    // 5c. Build ShaderGraph + Material
                    string sgPath = Path.Combine(UPDATE_DIR, $"{llmResponse.file_name}.shadergraph");
                    ShaderGraphBuilder.BuildShaderGraphFromLLMResponse(updatedHlslPath, sgPath, useTransparency: true);
                    AssetDatabase.Refresh();
                    await Task.Delay(1200);
                    AssetDatabase.Refresh();
                    await Task.Delay(400);

                    var shader = AssetDatabase.LoadAssetAtPath<Shader>(sgPath);
                    if (shader == null)
                    {
                        Debug.LogWarning($"[Update Pipeline] Shader not loaded on iter {iter} — skipping.");
                        continue;
                    }

                    string matPath = Path.Combine(UPDATE_DIR, $"{llmResponse.file_name}.mat");
                    if (AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(matPath) != null)
                        AssetDatabase.DeleteAsset(matPath);
                    var material = new Material(shader);
                    AssetDatabase.CreateAsset(material, matPath);
                    AssetDatabase.SaveAssets();
                    AssetDatabase.Refresh();

                    // Reload after refresh — the object reference may be stale post-reimport.
                    material = AssetDatabase.LoadAssetAtPath<Material>(matPath);

                    // Apply ALL properties returned by the LLM.
                    // The prompt instructs the LLM to return the FULL property list — keeping
                    // exact original values for unchanged params and updated values for changed/new ones.
                    // We must NOT use CopyPropertiesFromMaterial: it copies values from a different
                    // shader's property block, which silently fails or maps to wrong slots when the
                    // new shader has different or additional properties. Any property only on the new
                    // shader would be left at 0,0,0,0 (fully transparent / invisible).
                    if (llmResponse.properties != null && llmResponse.properties.Count > 0)
                        ShaderGraphGeneratorEditorUtility.SetDefaultMaterialProperties(material, llmResponse.properties);

                    // Persist so Unity uses the correct values at render time.
                    EditorUtility.SetDirty(material);
                    AssetDatabase.SaveAssets();

                    // 5d. Render AFTER screenshot (quad stays in scene)
                    string afterPath    = Path.Combine(PREVIEW_DIR, $"{llmResponse.file_name}_after_{iter}.png");
                    string afterAbsPath = ToAbsolutePath(afterPath);
                    Directory.CreateDirectory(Path.GetDirectoryName(afterAbsPath));
                    bool rendered = await RenderMaterialToImageAsync(material, afterAbsPath, keepQuad: true);
                    if (!rendered)
                    {
                        Debug.LogWarning($"[Update Pipeline] After render failed on iter {iter}.");
                        continue;
                    }

                    // 5e. VLM comparison evaluation (before vs after)
                    var eval = await EvaluateUpdateAsync(
                        updateRequest, result.beforeImagePath, afterAbsPath, config.openAIKey);

                    Debug.Log($"[Update Pipeline] VLM score: {eval.score}/10 — {eval.explanation}");

                    // Save best result so far
                    result.updatedFileName = llmResponse.file_name;
                    result.updatedHlslCode = llmResponse.hlsl_code;
                    result.properties      = llmResponse.properties;
                    result.shaderGraphPath = sgPath;
                    result.materialPath    = matPath;
                    result.afterImagePath  = afterAbsPath;
                    result.vlmScore        = eval.score;
                    result.vlmFeedback     = eval.explanation;

                    if (eval.score > VLM_ACCEPT_THRESHOLD)
                    {
                        result.success = true;
                        Debug.Log($"[Update Pipeline] ✓ Accepted at VLM iteration {iter}.");
                        return result;
                    }

                    previousVlmFeedback = eval.explanation;
                    currentHlsl         = llmResponse.hlsl_code;
                }

                // All VLM iterations exhausted — return best attempt anyway
                result.success      = false;
                result.errorMessage = $"VLM score never exceeded {VLM_ACCEPT_THRESHOLD} in {maxVlmIterations} iterations.";
                return result;
            }
            catch (Exception ex)
            {
                result.errorMessage = ex.Message;
                Debug.LogError($"[Update Pipeline] Exception: {ex.Message}\n{ex.StackTrace}");
                return result;
            }
        }

        // ─── Extract HLSL path from material's ShaderGraph ────────────────────

        /// <summary>
        /// Reads the .shadergraph asset referenced by the material's shader,
        /// finds the CustomFunctionNode's m_FunctionSource GUID, and resolves it to an HLSL path.
        /// </summary>
        private static string ExtractHlslPathFromMaterial(Material material)
        {
            string sgPath = AssetDatabase.GetAssetPath(material.shader);
            if (string.IsNullOrEmpty(sgPath) || !File.Exists(sgPath))
            {
                Debug.LogWarning("[Update Pipeline] Material's shader asset not found on disk.");
                return null;
            }

            string sgJson = File.ReadAllText(sgPath);
            var match = Regex.Match(sgJson, @"""m_FunctionSource""\s*:\s*""([a-f0-9A-F]+)""");
            if (!match.Success)
            {
                Debug.LogWarning("[Update Pipeline] No m_FunctionSource GUID found in ShaderGraph.");
                return null;
            }

            string guid     = match.Groups[1].Value;
            string hlslPath = AssetDatabase.GUIDToAssetPath(guid);
            if (string.IsNullOrEmpty(hlslPath))
            {
                Debug.LogWarning($"[Update Pipeline] GUID {guid} could not be resolved to an asset path.");
                return null;
            }

            return hlslPath;
        }

        // ─── Extract current property values from a material ──────────────────

        /// <summary>
        /// Reads all Float, Range, Vector, and Color properties from a material
        /// and returns them as LLMShaderProperty list (the same format LLM outputs).
        /// </summary>
        private static List<LLMShaderProperty> ExtractMaterialProperties(Material material)
        {
            var result = new List<LLMShaderProperty>();

            MaterialProperty[] props;
            try
            {
                props = MaterialEditor.GetMaterialProperties(new UnityEngine.Object[] { material });
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[Update Pipeline] Could not read material properties: {ex.Message}");
                return result;
            }

            foreach (var prop in props)
            {
                // Skip Unity internal / texture properties
                if (prop.name.StartsWith("unity_", StringComparison.OrdinalIgnoreCase)) continue;
                if (prop.type == MaterialProperty.PropType.Texture) continue;

                LLMShaderProperty sp = null;

                switch (prop.type)
                {
                    case MaterialProperty.PropType.Float:
                    case MaterialProperty.PropType.Range:
                        sp = new LLMShaderProperty
                        {
                            name          = prop.name,
                            type          = "float",
                            default_value = new LLMValueObject(prop.floatValue)
                        };
                        break;

                    case MaterialProperty.PropType.Vector:
                        sp = new LLMShaderProperty
                        {
                            name          = prop.name,
                            type          = "float4",
                            default_value = new LLMValueObject(
                                prop.vectorValue.x, prop.vectorValue.y,
                                prop.vectorValue.z, prop.vectorValue.w)
                        };
                        break;

                    case MaterialProperty.PropType.Color:
                        sp = new LLMShaderProperty
                        {
                            name          = prop.name,
                            type          = "float4",
                            default_value = new LLMValueObject(
                                prop.colorValue.r, prop.colorValue.g,
                                prop.colorValue.b, prop.colorValue.a)
                        };
                        break;
                }

                if (sp != null) result.Add(sp);
            }

            return result;
        }

        // ─── shared render helper ─────────────────────────────────────────────

        private static async Task<bool> RenderMaterialToImageAsync(
            Material material, string outputPath, bool keepQuad)
        {
            // Hide all existing renderers
            var allRenderers = UnityEngine.Object.FindObjectsByType<Renderer>(FindObjectsSortMode.None);
            var wasEnabled   = new bool[allRenderers.Length];
            for (int i = 0; i < allRenderers.Length; i++)
            {
                wasEnabled[i]           = allRenderers[i].enabled;
                allRenderers[i].enabled = false;
            }

            GameObject quad      = null;
            GameObject cameraGO  = null;
            Camera     cam       = null;
            RenderTexture rt     = null;
            Texture2D screenshot = null;

            try
            {
                quad = GameObject.CreatePrimitive(PrimitiveType.Quad);
                quad.name = $"UpdatePreview — {material.name}";
                quad.GetComponent<Renderer>().material = material;
                quad.transform.SetPositionAndRotation(Vector3.zero, Quaternion.identity);
                quad.transform.localScale = Vector3.one;

                if (keepQuad)
                {
                    Selection.activeGameObject = quad;
                    if (SceneView.lastActiveSceneView != null)
                        SceneView.lastActiveSceneView.FrameSelected();
                }

                cameraGO = new GameObject("_UpdateRenderCamera");
                cam      = cameraGO.AddComponent<Camera>();
                cam.transform.position = new Vector3(0f, 0f, -2f);
                cam.transform.LookAt(quad.transform);
                cam.clearFlags       = CameraClearFlags.SolidColor;
                cam.backgroundColor  = Color.white;
                cam.orthographic     = true;
                cam.orthographicSize = 0.55f;
                cam.cullingMask      = 1 << quad.layer;

                rt                = new RenderTexture(512, 512, 24);
                cam.targetTexture = rt;

                await Task.Delay(100);
                cam.Render();

                RenderTexture.active = rt;
                screenshot = new Texture2D(512, 512, TextureFormat.RGBA32, false);
                screenshot.ReadPixels(new Rect(0, 0, 512, 512), 0, 0);
                screenshot.Apply();

                // Composite transparent pixels over white
                var pixels = screenshot.GetPixels32();
                for (int i = 0; i < pixels.Length; i++)
                {
                    float a     = pixels[i].a / 255f;
                    pixels[i].r = (byte)(pixels[i].r * a + 255 * (1f - a));
                    pixels[i].g = (byte)(pixels[i].g * a + 255 * (1f - a));
                    pixels[i].b = (byte)(pixels[i].b * a + 255 * (1f - a));
                    pixels[i].a = 255;
                }
                screenshot.SetPixels32(pixels);
                screenshot.Apply();

                File.WriteAllBytes(outputPath, screenshot.EncodeToPNG());
                Debug.Log($"[Update Pipeline] Screenshot saved: {outputPath}");
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Update Pipeline] Render failed: {ex.Message}");
                return false;
            }
            finally
            {
                RenderTexture.active = null;
                // Detach RT from camera before releasing it, otherwise Unity throws a warning.
                if (cam != null) cam.targetTexture = null;
                if (rt         != null) { rt.Release(); UnityEngine.Object.DestroyImmediate(rt); }
                if (screenshot != null) UnityEngine.Object.DestroyImmediate(screenshot);
                if (cameraGO   != null) UnityEngine.Object.DestroyImmediate(cameraGO);
                if (!keepQuad && quad != null) UnityEngine.Object.DestroyImmediate(quad);

                for (int i = 0; i < allRenderers.Length; i++)
                    if (allRenderers[i] != null)
                        allRenderers[i].enabled = wasEnabled[i];

                AssetDatabase.Refresh();
            }
        }

        // ─── KB retrieval ─────────────────────────────────────────────────────

        private static async Task<List<RetrievedExample>> RetrieveExamplesAsync(
            string updateRequest, ShapeKnowledgeBase kb, string openAIKey)
        {
            var examples = new List<RetrievedExample>();
            var results  = await SemanticShapeSearch.SearchAsync(updateRequest, kb, openAIKey, topK: 3);

            foreach (var r in results)
            {
                if (!File.Exists(r.shape.filePath)) continue;
                examples.Add(new RetrievedExample
                {
                    componentRole           = "reference",
                    componentDescription    = updateRequest,
                    matchedShapeName        = r.shape.fileName,
                    matchedShapePrompt      = r.shape.originalPrompt,
                    matchedShapeDescription = r.shape.visualDescription,
                    hlslCode                = File.ReadAllText(r.shape.filePath),
                    similarityScore         = r.similarity
                });
                Debug.Log($"[Update Pipeline]   Retrieved: {r.shape.fileName} (sim={r.similarity:F3})");
            }
            return examples;
        }

        // ─── helpers ─────────────────────────────────────────────────────────

        /// Converts an Assets-relative path to an absolute filesystem path.
        /// File I/O (File.Exists, File.ReadAllBytes) needs absolute paths because
        /// Unity's CWD can shift after AssetDatabase.Refresh() / domain reloads.
        private static string ToAbsolutePath(string assetPath)
        {
            if (string.IsNullOrEmpty(assetPath)) return assetPath;
            if (Path.IsPathRooted(assetPath)) return assetPath;
            // Application.dataPath = "<ProjectRoot>/Assets"
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            return Path.GetFullPath(Path.Combine(projectRoot, assetPath));
        }

        // ─── VLM comparison evaluation ────────────────────────────────────────

        private static async Task<LLMMatchScoreResponse> EvaluateUpdateAsync(
            string updateRequest, string beforePath, string afterPath, string openAIKey)
        {
            string beforeAbs = ToAbsolutePath(beforePath);
            string afterAbs  = ToAbsolutePath(afterPath);

            if (string.IsNullOrEmpty(beforeAbs) || !File.Exists(beforeAbs))
            {
                Debug.LogWarning($"[Update Pipeline] No before image at '{beforeAbs}' — cannot compare. Returning mid score.");
                return new LLMMatchScoreResponse { score = 5, explanation = "No before image available." };
            }

            string json = await LLMApiService.CallOpenAIUpdateEvalAsync(
                updateRequest, beforeAbs, afterAbs, openAIKey);

            if (string.IsNullOrEmpty(json))
                return new LLMMatchScoreResponse { score = 0, explanation = "VLM evaluation failed." };

            try   { return JsonConvert.DeserializeObject<LLMMatchScoreResponse>(json); }
            catch { return new LLMMatchScoreResponse { score = 0, explanation = "Could not parse VLM response." }; }
        }

        // ─── prompt builder ───────────────────────────────────────────────────

        private static string BuildUpdatePrompt(
            string originalHlsl, string currentHlsl,
            string updateRequest,
            List<LLMShaderProperty> originalProperties,
            List<RetrievedExample>  examples,
            string prevVlmFeedback, string userFeedback, int iteration)
        {
            var sb = new StringBuilder();

            sb.AppendLine("You are an expert HLSL shader developer for Unity ShaderGraph Custom Function Nodes.");
            sb.AppendLine("Your task: UPDATE an existing HLSL shader to satisfy the user's specific request.");
            sb.AppendLine();
            sb.AppendLine("## CRITICAL RULES");
            sb.AppendLine("- Preserve the EXACT same function signature style:  void Name_float(float2 UV, ..., out float4 outColor)");
            sb.AppendLine("- You MAY add new parameters but must KEEP all existing ones");
            sb.AppendLine("- Change ONLY what the update request asks — preserve everything else visually");
            sb.AppendLine("- Use HLSL intrinsics only: lerp (not mix), frac (not fract), fmod (not mod)");
            sb.AppendLine("- Helper functions must be defined BEFORE the main function");
            sb.AppendLine();

            sb.AppendLine("## ORIGINAL HLSL (do not regress from this baseline)");
            sb.AppendLine("```hlsl");
            sb.AppendLine(originalHlsl);
            sb.AppendLine("```");
            sb.AppendLine();

            if (iteration > 1 && !string.ReferenceEquals(originalHlsl, currentHlsl))
            {
                sb.AppendLine("## CURRENT BEST ATTEMPT (improve this, not the original)");
                sb.AppendLine("```hlsl");
                sb.AppendLine(currentHlsl);
                sb.AppendLine("```");
                sb.AppendLine();
            }

            sb.AppendLine("## USER UPDATE REQUEST");
            sb.AppendLine(updateRequest);
            sb.AppendLine();

            // Include the live material property values so the LLM can reproduce them exactly
            if (originalProperties != null && originalProperties.Count > 0)
            {
                sb.AppendLine("## CURRENT MATERIAL PROPERTY VALUES");
                sb.AppendLine("These are the EXACT values currently set on the material that produces the 'before' image.");
                sb.AppendLine("IMPORTANT: Your 'properties' array MUST include EVERY parameter in the updated shader function — both");
                sb.AppendLine("unchanged ones (copy exact values from the list below) and new/changed ones (assign appropriate values).");
                sb.AppendLine("Do NOT omit any parameter. If a parameter was removed by the update, omit only that one.");
                sb.AppendLine("For color/float4 properties: ALWAYS set w (alpha) to 1.0 unless you have a specific reason otherwise.");
                sb.AppendLine("NEVER return a color with w=0 — that makes it invisible.");
                sb.AppendLine();
                foreach (var p in originalProperties)
                {
                    var v = p.default_value;
                    string valStr = p.type == "float"
                        ? v.x.ToString("F4")
                        : $"{{x:{v.x:F4}, y:{v.y:F4}, z:{v.z:F4}, w:{v.w:F4}}}";
                    sb.AppendLine($"  {p.name} ({p.type}): {valStr}");
                }
                sb.AppendLine();
            }

            if (!string.IsNullOrEmpty(prevVlmFeedback))
            {
                sb.AppendLine("## VLM FEEDBACK FROM PREVIOUS ATTEMPT (address these issues)");
                sb.AppendLine(prevVlmFeedback);
                sb.AppendLine();
            }

            if (!string.IsNullOrEmpty(userFeedback))
            {
                sb.AppendLine("## HUMAN REVIEWER FEEDBACK (address these issues)");
                sb.AppendLine(userFeedback);
                sb.AppendLine();
            }

            if (examples.Count > 0)
            {
                sb.AppendLine("## RETRIEVED LIBRARY EXAMPLES (technique reference only)");
                foreach (var ex in examples)
                {
                    sb.AppendLine($"### {ex.matchedShapeName} (similarity: {ex.similarityScore:F2})");
                    if (!string.IsNullOrEmpty(ex.matchedShapeDescription))
                        sb.AppendLine($"Description: {ex.matchedShapeDescription}");
                    sb.AppendLine("```hlsl");
                    sb.AppendLine(ex.hlslCode);
                    sb.AppendLine("```");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("## OUTPUT FORMAT — return ONLY this JSON, no markdown, no extra text");
            sb.AppendLine("CRITICAL for the 'properties' array:");
            sb.AppendLine("- List ALL parameters in the updated shader function (not just changed ones).");
            sb.AppendLine("- For unchanged parameters: copy the EXACT value from 'CURRENT MATERIAL PROPERTY VALUES' above.");
            sb.AppendLine("- For new or changed parameters: assign a meaningful non-zero value.");
            sb.AppendLine("- float/float2/float3: scalar  e.g. 0.5");
            sb.AppendLine("- float4/color: object with w=1.0 for opaque  e.g. {\"x\":1.0,\"y\":0.2,\"z\":0.2,\"w\":1.0}");
            sb.AppendLine("- NEVER output {\"x\":0,\"y\":0,\"z\":0,\"w\":0} — if you have no good value, use the original from above.");
            sb.AppendLine(@"{
  ""file_name"": ""UpdatedShapeName"",
  ""hlsl_code"": ""[complete updated HLSL code]"",
  ""properties"": [
    { ""name"": ""ScarfStripeCount"", ""type"": ""float"", ""default_value"": 5 },
    { ""name"": ""ScarfStripeColor"", ""type"": ""float4"", ""default_value"": {""x"":1.0,""y"":1.0,""z"":0.0,""w"":1.0} }
  ]
}");
            return sb.ToString();
        }

        // ─── helpers ──────────────────────────────────────────────────────────

        private static string StripMarkdown(string text)
        {
            if (string.IsNullOrEmpty(text)) return text;
            var m = Regex.Match(text, @"```(?:json)?\s*([\s\S]*?)```",
                                RegexOptions.Multiline);
            return m.Success ? m.Groups[1].Value.Trim() : text.Trim();
        }

        private static void EnsureDirectories()
        {
            if (!Directory.Exists(UPDATE_DIR))  Directory.CreateDirectory(UPDATE_DIR);
            if (!Directory.Exists(PREVIEW_DIR)) Directory.CreateDirectory(PREVIEW_DIR);
        }
    }
}