using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEngine;
using ShaderGraphGenerator.KnowledgeBase;

namespace ShaderGraphGenerator.RAG
{
    /// <summary>
    /// Composes multiple HLSL SDF primitives into a single complex shape
    /// </summary>
    public static class HLSLCompositionEngine
    {
        /// <summary>
        /// Compose multiple retrieved shapes into a single HLSL function
        /// </summary>
        public static ComposedHLSL ComposeShapes(
            ShapeDecomposition decomposition,
            Dictionary<string, ShapeSearchResult> selectedComponents,
            string outputFunctionName)
        {
            var composed = new ComposedHLSL
            {
                functionName = outputFunctionName,
                components = new List<ComponentInfo>()
            };

            // If simple shape, just return the single component
            if (decomposition.is_simple && selectedComponents.Count == 1)
            {
                var component = selectedComponents.First();
                string hlslCode = File.ReadAllText(component.Value.shape.filePath);
                
                composed.hlslCode = hlslCode;
                composed.isSinglePrimitive = true;
                composed.components.Add(new ComponentInfo
                {
                    shapeName = component.Value.shape.fileName,
                    role = decomposition.components[0].role,
                    hlslCode = hlslCode
                });
                
                return composed;
            }

            // Build composite HLSL
            composed.isSinglePrimitive = false;
            composed.hlslCode = BuildCompositeHLSL(decomposition, selectedComponents, outputFunctionName, composed.components);
            
            return composed;
        }

        private static string BuildCompositeHLSL(
            ShapeDecomposition decomposition,
            Dictionary<string, ShapeSearchResult> selectedComponents,
            string functionName,
            List<ComponentInfo> componentInfos)
        {
            var sb = new StringBuilder();

            // Header comment
            sb.AppendLine("// ============================================");
            sb.AppendLine($"// Composite Shape: {functionName}");
            sb.AppendLine($"// Generated by RAG Composition Engine");
            sb.AppendLine($"// Components: {selectedComponents.Count}");
            sb.AppendLine("// ============================================");
            sb.AppendLine();

            // Extract and include helper functions from all components
            var helperFunctions = new HashSet<string>();
            foreach (var component in selectedComponents.Values)
            {
                string hlslCode = File.ReadAllText(component.shape.filePath);
                ExtractHelperFunctions(hlslCode, helperFunctions);
            }

            // Write helper functions
            foreach (var helper in helperFunctions)
            {
                sb.AppendLine(helper);
                sb.AppendLine();
            }

            // Write individual SDF functions for each component
            int componentIndex = 0;
            foreach (var kvp in selectedComponents)
            {
                string componentDesc = kvp.Key;
                var result = kvp.Value;
                
                string hlslCode = File.ReadAllText(result.shape.filePath);
                string wrappedFunction = WrapComponentFunction(hlslCode, componentIndex, result.shape.functionName);
                
                sb.AppendLine(wrappedFunction);
                sb.AppendLine();

                componentInfos.Add(new ComponentInfo
                {
                    shapeName = result.shape.fileName,
                    role = decomposition.components[componentIndex].role,
                    hlslCode = hlslCode,
                    transformHint = decomposition.components[componentIndex].position_hint
                });

                componentIndex++;
            }

            // Write main composition function
            sb.AppendLine(BuildMainCompositionFunction(functionName, decomposition, selectedComponents));

            return sb.ToString();
        }

        /// <summary>
        /// Extract helper functions (sdBox, smoothMin, etc.) from HLSL code
        /// </summary>
        private static void ExtractHelperFunctions(string hlslCode, HashSet<string> helpers)
        {
            var lines = hlslCode.Split('\n');
            bool inHelperFunction = false;
            var currentFunction = new StringBuilder();

            foreach (var line in lines)
            {
                string trimmed = line.Trim();

                // Detect start of helper function (float sdXXX or float smoothXXX, etc.)
                if (trimmed.StartsWith("float sd") || 
                    trimmed.StartsWith("float smooth") ||
                    trimmed.StartsWith("float2 ") ||
                    trimmed.Contains("Rotate2D") ||
                    trimmed.Contains("Transform"))
                {
                    // Check if it's NOT the main _float function
                    if (!trimmed.Contains("_float("))
                    {
                        inHelperFunction = true;
                        currentFunction.Clear();
                        currentFunction.AppendLine(line);
                        continue;
                    }
                }

                if (inHelperFunction)
                {
                    currentFunction.AppendLine(line);
                    
                    // End of function (closing brace at start of line)
                    if (trimmed == "}")
                    {
                        string funcText = currentFunction.ToString().Trim();
                        if (!string.IsNullOrEmpty(funcText))
                        {
                            helpers.Add(funcText);
                        }
                        inHelperFunction = false;
                    }
                }
            }
        }

        /// <summary>
        /// Wrap a component's main function to be callable with a unique name
        /// </summary>
        private static string WrapComponentFunction(string originalHlsl, int componentIndex, string originalFunctionName)
        {
            // Extract just the main function body
            string functionBody = ExtractMainFunctionBody(originalHlsl, originalFunctionName);
            
            return $@"// Component {componentIndex}: {originalFunctionName}
float Component{componentIndex}_SDF(float2 uv, float2 offset, float scale, float rotation)
{{
    // Apply transformations
    uv -= offset;
    uv /= scale;
    
    if (rotation != 0.0)
    {{
        float c = cos(rotation);
        float s = sin(rotation);
        uv = float2(uv.x * c - uv.y * s, uv.x * s + uv.y * c);
    }}
    
    // Call original SDF
{IndentCode(functionBody, "    ")}
    
    return d;
}}";
        }

        /// <summary>
        /// Extract the main SDF calculation from a function
        /// </summary>
        private static string ExtractMainFunctionBody(string hlslCode, string functionName)
        {
            var lines = hlslCode.Split('\n');
            bool inMainFunction = false;
            var body = new StringBuilder();
            int braceDepth = 0;

            foreach (var line in lines)
            {
                if (line.Contains($"{functionName}_float(") || line.Contains("void " + functionName))
                {
                    inMainFunction = true;
                    continue;
                }

                if (inMainFunction)
                {
                    if (line.Contains("{")) braceDepth++;
                    if (line.Contains("}")) braceDepth--;

                    if (braceDepth == 0 && line.Contains("}"))
                    {
                        break;
                    }

                    // Skip the outColor assignment at the end
                    if (line.Trim().StartsWith("outColor") || line.Trim().StartsWith("Out ="))
                        continue;

                    body.AppendLine(line);
                }
            }

            return body.ToString();
        }

        /// <summary>
        /// Build the main composition function that combines all components
        /// </summary>
        private static string BuildMainCompositionFunction(
            string functionName,
            ShapeDecomposition decomposition,
            Dictionary<string, ShapeSearchResult> selectedComponents)
        {
            var sb = new StringBuilder();

            // Function signature
            sb.AppendLine($"void {functionName}_float(");
            sb.AppendLine("    float2 UV,");
            
            // Add parameters for each component (offset, scale, rotation)
            for (int i = 0; i < selectedComponents.Count; i++)
            {
                sb.AppendLine($"    float2 Component{i}_Offset,");
                sb.AppendLine($"    float Component{i}_Scale,");
                sb.AppendLine($"    float Component{i}_Rotation,");
            }
            
            sb.AppendLine("    float4 Color,");
            sb.AppendLine("    out float4 Out");
            sb.AppendLine(")");
            sb.AppendLine("{");
            sb.AppendLine("    float2 uv = UV - 0.5;");
            sb.AppendLine();

            // Call each component SDF
            for (int i = 0; i < selectedComponents.Count; i++)
            {
                sb.AppendLine($"    float d{i} = Component{i}_SDF(uv, Component{i}_Offset, Component{i}_Scale, Component{i}_Rotation);");
            }

            sb.AppendLine();

            // Combine using union (can be made smarter later)
            sb.AppendLine("    // Combine all components using smooth union");
            sb.AppendLine($"    float finalDistance = d0;");
            
            for (int i = 1; i < selectedComponents.Count; i++)
            {
                sb.AppendLine($"    finalDistance = min(finalDistance, d{i}); // Union operation");
            }

            sb.AppendLine();
            sb.AppendLine("    // Anti-aliased rendering");
            sb.AppendLine("    float alpha = smoothstep(0.01, -0.01, finalDistance);");
            sb.AppendLine("    Out = float4(Color.rgb, alpha * Color.a);");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string IndentCode(string code, string indent)
        {
            var lines = code.Split('\n');
            return string.Join("\n", lines.Select(line => indent + line));
        }

        /// <summary>
        /// Generate default parameter values based on decomposition hints
        /// </summary>
        public static Dictionary<string, object> GenerateDefaultParameters(
            ShapeDecomposition decomposition,
            Dictionary<string, ShapeSearchResult> selectedComponents)
        {
            var parameters = new Dictionary<string, object>();

            for (int i = 0; i < decomposition.components.Count; i++)
            {
                var component = decomposition.components[i];
                
                // Parse position hint to generate offset
                var offset = ParsePositionHint(component.position_hint, component.relative_size);
                
                parameters[$"Component{i}_Offset"] = offset;
                parameters[$"Component{i}_Scale"] = ParseRelativeSize(component.relative_size);
                parameters[$"Component{i}_Rotation"] = 0f;
            }

            parameters["Color"] = new float[] { 1f, 1f, 1f, 1f };

            return parameters;
        }

        private static float[] ParsePositionHint(string hint, string relativeSize)
        {
            // Default center
            float x = 0f, y = 0f;

            if (string.IsNullOrEmpty(hint))
                return new float[] { x, y };

            hint = hint.ToLower();

            // Vertical positioning
            if (hint.Contains("top"))
                y = 0.15f;
            else if (hint.Contains("bottom"))
                y = -0.15f;

            // Horizontal positioning
            if (hint.Contains("left"))
                x = -0.15f;
            else if (hint.Contains("right"))
                x = 0.15f;

            return new float[] { x, y };
        }

        private static float ParseRelativeSize(string relativeSize)
        {
            switch (relativeSize?.ToLower())
            {
                case "small": return 0.3f;
                case "medium": return 0.5f;
                case "large": return 0.8f;
                default: return 0.5f;
            }
        }
    }

    /// <summary>
    /// Result of HLSL composition
    /// </summary>
    [Serializable]
    public class ComposedHLSL
    {
        public string functionName;
        public string hlslCode;
        public bool isSinglePrimitive;
        public List<ComponentInfo> components = new List<ComponentInfo>();
    }

    /// <summary>
    /// Information about a component used in composition
    /// </summary>
    [Serializable]
    public class ComponentInfo
    {
        public string shapeName;
        public string role;
        public string hlslCode;
        public string transformHint;
    }
}